app/forms/category.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField

from wtforms.validators import DataRequired


# Category form
class CategoryForm(FlaskForm):

    title = StringField(label="Titre", validators=[DataRequired()])
    submit = SubmitField(label="Créer Category")

app/views/category.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from flask_login import current_user, login_required
from app.models.Model import Category, ACCESS
from flask import current_app as app
from app import db
from app.utils.utils import requires_access_level
from app.forms.category import CategoryForm

category = Blueprint('category', __name__)

@category.route('/categories')
@login_required
def categories():
    title = "categories"
    categories = Category.query.all()
    return render_template('categories/index.html',title=title, categories=categories)

@category.route('/new-category', methods=['GET', 'POST'])
@login_required
@requires_access_level(ACCESS['admin'])
def new_category():
    title = "ajoutée categorie"
    form = CategoryForm()

    if request.method == 'GET':
      return render_template('categories/create_category.html', title=title, form=form)

    if form.validate_on_submit():
        title = request.form.get("title")
        
        category = Category(title)

        db.session.add(category)
        db.session.commit()

        flash('Votre category a été ajoutée!')

        return redirect(url_for('category.new_category'))
    else:
      return render_template("categories/create_category.html", title=title, form=form)

@category.route('/edit-category/<int:id>', methods=['GET', 'POST'])
@login_required
@requires_access_level(ACCESS['admin'])
def edit_category(id):
  title = "Edit Category"
  form = CategoryForm()
  category = Category.query.filter_by(id=id).first()

  if request.method == 'GET':

    form.title.data = category.title
    return render_template('categories/edit_category.html', title=title, form=form, category=category)

  if form.validate_on_submit():
    
    title = request.form.get("title")
    
    category.title = title

    db.session.commit()

    flash('Votre category a été modifiée!')
    return redirect(url_for('category.categories'))

  else:
    return render_template('categories/edit_category.html', title=title, form=form, category=category)


@category.route('/delete-category/<int:id>', methods=['GET', 'POST'])
@login_required
@requires_access_level(ACCESS['admin'])
def delete(id):
  category = Category.query.filter_by(id=id).delete()
  
  db.session.commit()
  return redirect(url_for('category.categories'))

app/templates/categories/create_category.html
{% extends "base.html" %} {% block title %}{{ title }}{% endblock %} {% block
content %}
<div class="container tasks-new-task col-md-6">
  <h2>ajouter une nouvelle category</h2>
  {% with messages = get_flashed_messages() %}
    {% if messages %}
      <div class="alert alert-success">
        {{ messages[0] }}
      </div>
    {% endif %}
  {% endwith %}
  <form
    action="{{ url_for('category.new_category') }}"
    method="POST"
    enctype="multipart/form-data"
  >
    <div class="form-group">
      {{ form.csrf_token }}
      <div class="form-group">
        {{ form.title.label }} {{ form.title(class='form-control',
        placeholder='Ajouter le titre de category', autocomplete="off") }}
      </div>
      <div class="form-group form-btn">
        {{ form.submit(class='btn btn-primary') }}
      </div>
    </div>
  </form>
</div>
{% endblock %}

app/templates/categories/edit_category.html
{% extends "base.html" %} {% block title %}{{ title }}{% endblock %} {% block
content %}
<div class="container tasks-new-task col-md-6">
  <h2>Editer Category</h2>
  {% with messages = get_flashed_messages() %}
    {% if messages %}
      <div class="alert alert-danger">
        {{ messages[0] }}
      </div>
    {% endif %}
  {% endwith %}
  <form
    action="{{ url_for('category.edit_category', id=category.id) }}"
    method="POST"
    enctype="multipart/form-data"
  >
    <div class="form-group">
      {{ form.csrf_token }}
      <div class="form-group">
        {{ form.title.label }} {{ form.title(class='form-control',
        placeholder='Ajouter le titre de category',
        value=category.title) }}
      </div>
      <div class="form-group form-btn">
        {{ form.submit(class='btn btn-primary', value="modifié category") }}
      </div>
    </div>
  </form>
</div>
{% endblock %}

app/templates/categories/index.html
{% extends "base.html" %} {% block title %}{{ title }}{% endblock %} {% block
content %}

<div class="container all-tasks col-md-8">
  <table class="table table-striped">
    <div>
      <h2>All categories</h2>
    </div>
    <a class="add-category-btn" href="{{ url_for('category.new_category') }}">Ajouter categorie</a>
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Titre de categorie</th>
        <th scope="col">number of employees</th>
        <th scope="col">Opérations</th>
      </tr>
    </thead>
    {% if categories|length <= 0 %} 
    <tbody>
      <tr>
        <td colspan="5" class="no-tasks">Il n'y a pas encore des categories.</td>
      </tr>
    </tbody>
    {% else %}
    <tbody>
      {% with messages = get_flashed_messages() %}
        {% if messages %}
          <div class="alert alert-success">
            {{ messages[0] }}
          </div>
        {% endif %}
      {% endwith %}
      {% for category in categories %}
      <tr>
        <th scope="row">{{ loop.index }}</th>
        <td>{{ category.title }}</td>
        <td> {{ category.users.all()|length }} </td>
        <td class="crud-operations">
          <a href="{{ url_for('category.edit_category', id=category.id) }}">
            <i class="fa fa-pencil" aria-hidden="true"></i>
          </a>
          <form
            id="delete-category"
            action="{{ url_for('category.delete', id=category.id) }}"
            style="display: inline"
            method="POST"
          >
            <button type="submit">
              <i class="fa fa-trash" aria-hidden="true"></i>
            </button>
          </form>
        </td>
      </tr>
      {% endfor %}
    </tbody>
    {% endif %}
  </table>
</div>

{% endblock %}