app/forms/task.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, DateField, SelectField
from flask_wtf.file import FileField, FileRequired
from wtforms.validators import DataRequired, Required
from wtforms.widgets import TextArea
from datetime import datetime
from app.models.Model import User

def get_users():
    users_query = User.query.all()
    users = []

    for user in users_query:
        users.append((user.id,user.username)) 

    return users

# Task form
class TaskForm(FlaskForm):

    title = StringField(label="Titre", validators=[DataRequired()])
    description = StringField(label="Description", validators=[DataRequired()], widget=TextArea())
    image = FileField(validators=[FileRequired()])
    date = DateField('Date de la tache', validators=[Required()], format='%d/%m/%Y', default=datetime.today)
    user = SelectField('Attribuez la tâche à', validators=[DataRequired()],choices=get_users())
    submit = SubmitField(label="Créer Tache")

app/views/task.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, send_file
from flask_login import current_user, login_required
from app.models.Model import User, Task,Category , ACCESS
from app.forms.task import TaskForm
from werkzeug.utils import secure_filename
import os
from flask import current_app as app
from app import db
from datetime import datetime
from app.utils.utils import requires_access_level

task = Blueprint('task', __name__)

def convert(date_time): 
    format = '%d/%m/%Y'
    datetime_str = datetime.strptime(date_time, format) 
    return datetime_str

@task.route('/tasks')
@login_required
def tasks():
    title = "Taches"
    category = Category.query.filter_by(id=current_user.category_id).first()
    users = category.users.all()

    if current_user.is_admin():
      tasks = Task.query.order_by(Task.date.asc()).all()
    else:
      tasks = []
      for user in users:
        for task in user.tasks.order_by(Task.date.asc()).all():
          tasks.append(task)

    return render_template('tasks/index.html',title=title, tasks=tasks)

@task.route('/new-task', methods=['GET', 'POST'])
@login_required
#@requires_access_level(ACCESS['admin'])
def new_task():
    title = "Ajouter Tache"
    form = TaskForm()
    if request.method == 'GET':
      return render_template('tasks/create_task.html', title=title, form=form)

    if form.validate_on_submit():
        title = request.form.get("title")
        description = request.form.get("description")
        f = form.image.data
        filename = secure_filename(f.filename)
        f.save(os.path.join(app.instance_path, 'photos', filename))
        date = request.form.get("date")
        user_id = request.form.get("user")
        
        task = Task(title,description,filename,convert(date),user_id)

        user = User.query.filter_by(id=user_id).first()

        user.tasks.append(task)

        db.session.add(task)
        db.session.commit()

        flash('Votre tâche a été ajoutée!')

        return redirect(url_for('task.new_task'))
    else:
      return render_template("tasks/create_task.html", title=title, form=form)

@task.route('/download/<int:id>')
@login_required
def download(id):
    task = Task.query.filter_by(id=id).first()
    title = task.title
    filename = task.image
    file = os.path.join(app.instance_path, "photos" ,filename)
    return send_file(file)

@task.route('/complete/<int:id>')
@login_required
def complete(id):
  task = Task.query.filter_by(id=id).first()
  task.complete = True
  db.session.commit()
  return redirect(url_for('task.tasks'))

@task.route('/delete/<int:id>', methods=['POST'])
@login_required
def delete(id):
  task = Task.query.filter_by(id=id).delete()
  
  db.session.commit()
  return redirect(url_for('task.tasks'))

@task.route('/edit/<int:id>', methods=['GET', 'POST'])
@login_required
def edit_task(id):
  title = "Edit Tache"
  form = TaskForm()
  task = Task.query.filter_by(id=id).first()

  if request.method == 'GET':
    form.user.default = task.user.id
    form.process()

    form.description.data = task.description
    form.date.data = task.date
    return render_template('tasks/edit_task.html', title=title, form=form, task=task)

  if form.validate_on_submit():
    f = form.image.data
    filename = secure_filename(f.filename)
    if filename != task.image:
      f.save(os.path.join(app.instance_path, 'photos', filename))
    
    title = request.form.get("title")
    description = request.form.get("description")
    date = request.form.get("date")
    user_id = request.form.get("user")

    task = Task(title,description,filename,convert(date),user_id)

    user = User.query.filter_by(id=user_id).first()

    if user != task.user:
      user.tasks.append(task)
    
    db.session.commit()

    flash('Votre tâche a été modifiée!')
    return redirect(url_for('task.tasks'))

  else:
    return render_template('tasks/edit_task.html', title=title, form=form, task=task)

app/templates/tasks/create_task.html
{% extends "base.html" %} {% block title %}{{ title }}{% endblock %} {% block
content %}
<div class="container tasks-new-task col-md-6">
  <h2>ajouter une nouvelle tâche</h2>
  {% with messages = get_flashed_messages() %}
    {% if messages %}
      <div class="alert alert-success">
        {{ messages[0] }}
      </div>
    {% endif %}
  {% endwith %}
  <form
    action="{{ url_for('task.new_task') }}"
    method="POST"
    enctype="multipart/form-data"
  >
    <div class="form-group">
      {{ form.csrf_token }}
      <div class="form-group">
        {{ form.title.label }} {{ form.title(class='form-control',
        placeholder='Ajouter le titre de tache', autocomplete="off") }}
      </div>
      <div class="form-group">
        {{ form.description.label }} {{ form.description(class='form-control',
        placeholder='Ajouter la description de tache') }}
      </div>
      <div class="form-group">
        {{ form.image.label }} {{ form.image(class='form-control') }}
      </div>
      <div class="form-group">
        {{ form.date.label }} {{ form.date(class='form-control date datepicker')
        }}
      </div>
      <div class="form-group">
        {{ form.user.label }} {{ form.user(class='form-control') }}
      </div>
      <div class="form-group form-btn">
        {{ form.submit(class='btn btn-primary') }}
      </div>
    </div>
  </form>
</div>
{% endblock %}

app/templates/tasks/edit_task.html
{% extends "base.html" %} {% block title %}{{ title }}{% endblock %} {% block
content %}
<div class="container tasks-new-task col-md-6">
  <h2>Editer Tâche</h2>
  {% with messages = get_flashed_messages() %}
    {% if messages %}
      <div class="alert alert-danger">
        {{ messages[0] }}
      </div>
    {% endif %}
  {% endwith %}
  <form
    action="{{ url_for('task.edit_task', id=task.id) }}"
    method="POST"
    enctype="multipart/form-data"
  >
    <div class="form-group">
      {{ form.csrf_token }}
      <div class="form-group">
        {{ form.title.label }} {{ form.title(class='form-control',
        placeholder='Ajouter le titre de tache',
        value=task.title,
        autocomplete="off") }}
      </div>
      <div class="form-group">
        {{ form.description.label }} {{ form.description(class='form-control',
        value=task.description,
        placeholder='Ajouter la description de tache') }}
      </div>
      <div class="form-group">
        {{ form.image.label }} {{ form.image(class='form-control') }}
      </div>
      <div class="form-group">
        {{ form.date.label }} {{ form.date(class='form-control date datepicker')
        }}
      </div>
      <div class="form-group">
        {{ form.user.label }} {{ form.user(class='form-control') }}
      </div>
      <div class="form-group form-btn">
        {{ form.submit(class='btn btn-primary') }}
      </div>
    </div>
  </form>
</div>
{% endblock %}

app/templates/tasks/index.html
{% extends "base.html" %} {% block title %}{{ title }}{% endblock %} {% block
content %}

<div class="container all-tasks col-md-11">
  <table class="table table-striped">
    <div>
      <h2>All Taches</h2>
    </div>
    <a class="add-category-btn" href="{{ url_for('task.new_task') }}">Ajouter tâche</a>
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Titre de tache</th>
        <th scope="col">Assignée à</th>
        <th scope="col">Date</th>
        <th scope="col">Statut</th>
        <th scope="col">Opérations</th>
      </tr>
    </thead>
    {% if tasks|length <= 0 %} 
    <tbody>
      <tr>
        <td colspan="5" class="no-tasks">Il n'y a pas encore des tâches.</td>
      </tr>
    </tbody>
    {% else %}
    <tbody>
      {% with messages = get_flashed_messages() %}
        {% if messages %}
          <div class="alert alert-success">
            {{ messages[0] }}
          </div>
        {% endif %}
      {% endwith %}
      {% for task in tasks %}
      <tr>
        <th scope="row">{{ loop.index }}</th>
        <td class="show-todo-title">{{ task.title }}</td>
        <td>{{ task.user.username }}</td>
        <td>
          {{ task.date.strftime('%d-%m-%Y') }}
        </td>
        <td>
          {% if task.complete %}
          <span class="task-completed">Terminé</span>
          {% else %}
          <span class="task-uncompleted">Incomplète</span>
          {% endif %}
        </td>
        <td class="crud-operations">
          {% if current_user.id == task.user.id or current_user.is_admin() %}
          <a href="{{ url_for('task.complete', id=task.id) }}">
            <i class="fa fa-check" aria-hidden="true"></i>
          </a>
          <a href="{{ url_for('task.edit_task', id=task.id) }}">
            <i class="fa fa-pencil" aria-hidden="true"></i>
          </a>
          <a href="{{ url_for('task.download', id=task.id) }}" target="_blank">
            <i class="fa fa-download" aria-hidden="true"></i>
          </a>
          {% endif %}
          {% if current_user.is_admin() %}
          <form
            id="delete-task"
            action="{{ url_for('task.delete', id=task.id) }}"
            style="display: inline"
            method="POST"
          >
            <button type="submit">
              <i class="fa fa-trash" aria-hidden="true"></i>
            </button>
          </form>
          {% endif %}
        </td>
      </tr>
      {% endfor %}
    </tbody>
    {% endif %}
  </table>
</div>

{% endblock %}